#database:
  #host: "www.host.fr"
  #databasename: "dbname"
  #user: ""
  #password: "root"
  #port: 3306

database:
  host: "db1.falix.cc"
  databasename: "s662282_dotbase"
  user: "u662282_5nQmhRSsC7"
  password: "vall6WWwV@oz6B.z!rY+f@UB"
  port: 3306

commands:
  error_not_permission: "&&cTu n'a pas la permission d'executer cette commande !"
  error_cant_execute_in_console: "&&cCette commande ne peut pas être executer en console !"
  5_second_message: "&&aTu sera tp dans 5 seconde."
  wait_message: "&&cTu ne peut pas faire cette commande avant %time% secondes !"
  not_connected: "&&cCe joueur ne s'est jamais connecté au serveur !"
  unknow_player: "&&cCe joueur n'est pas connecter ou est inexistant."
  adminchat:
    activate: "&&aTu a activer l'admin chat."
    deactivate: "&&aTu a desactiver l'admin chat."
  setlobby:
    success: "&&aVous avez bien set le lobby dans le monde &&6%loc_world% &&aa vos coordonn//ees."
  lobby:
    success: "&&aVous avez //et//e t//el//eporter au lobby."
    error: "&&cLe lobby n'a pas //et//e d//efini."
  setspawn:
    success: "&&aVous avez bien set le spawn du monde &&6%loc_world% &&aa vos coordonn//ees."
  spawn:
    success: "&&aVous avez bien //et//e t//el//eporter au spawn du monde &&6%loc_world%&&a."
    error: "&&cLe spawn n'a pas //et//e d//efini dans ce monde."
  gamemode:
    me: "&&aVotre gamemode a //et//e changer en &&6%player_gamemode%."
    other: "&&aLe gamemode de %player_name% a //et//e changer en &&6%player_gamemode%&&a."
    unknow_gamemode: "&&cLe gamemode est incorect."
  freeze:
    freezeme: "&&aTu a freeze &&6%player_name%."
    freezeother: "&&aTu a //et//e freeze par &&6%player_name%."
    unfreezeme: "&&aTu a unfreeze &&6%player_name%."
    unfreezeother: "&&aTu a //et//e unfreeze par &&6%player_name%."
    errormsg: "&&cCe joueur n'est pas connecter ou est inexistant."
  fly:
    active: "&&aTu a activer ton fly."
    unactive: "&&aTu a d//esactiver ton fly."
    activeother: "&&aTu a activer le fly de %player_name%."
    unactiveother: "&&aTu a d//esactiver le fly de %player_name%."
  mute:
    mute_me: "&&aTu a mute &&6%player_name%."
    unmute_me: "&&aTu a unmute &&6%player_name%."
    mute_other: "&&cTu a //et//e mute par &&6%player_name%."
    unmute_other: "&&cTu a //et//e mute par &&6%player_name%."
  alert:
    alertformat: "&&4[Message Inportant] &&r%event_message%"
  ban:
    success: "&&aVous avez banni &&6%player_name% &&b(%ban_duration%) &&apour : &&e%ban_reason%"
    unknow_time_unit: "&&cCette unit//e de temps n'existe pas !"
    duration_not_number: "&&cLa valeur 'dur//ee' doit etre un nombre !"
    already_banned: "&&cCe joueur est déjà banni !"
  unban:
    succes: "&&aVous avez debanni &&6%player_name%."
    not_ban: "&&cCe joueur n'est pas banni !"
  nick:
    success_me: "&&aVous avez changer votre nickname en &&6%player_nickname%"
    success_other: "&&aVous avez changer le nickname de &&6%player_name% en &&6%player_nickname%."
    delete_me: "&&aVous avez suprimer votre nickname."
    delete_other: "&&aVous avez suprimer le nickname de %player_name%."
    delete_error_me: "&&cVous n'avez d//efini aucun nickname !"
    delete_error_other: "&&cCe joueur n'a aucun nickname !"
  permissions:
    success: "&&aVous avez modifier le power de la permission &&6%permissions_name% &&aen &&6%permissions_power%"
    unknow_power: "&&cLa valeur 'power' doit être un nombre !"
    unknow_permissions: "&&cLa permission est incorect !"
  ranks:
    create:
      success: "&&aLe rank &&6%rank_name% &&aa bien //et//e cr//eer."
      unknow_power: "&&cVeuiller entrer un nombre dans la valeur 'power' !"
      unknow_default: "&&cLa valeur 'true/false' doit être un boolean !"
      already_exist: "&&cLe rank &&6%rank_name% &&cexiste déjà !"
    join:
      success: "&&aVous avez ajouter &&6%player_name%&&a //a &&6%rank_name% &&aavec succes."
      unknow_rank: "&&cLe rank &&6%rank_name% &&cn'existe pas !"
      already_join: "&&cLe joueur &&6%player_name%&&c a d//ej//a le rank &&6%rank_name% &&c!"
    delete:
      success: "&&aLe rank &&6%rank_name% &&aa //et//e suprimer."
      unknow_rank: "&&cLe rank &&6%rank_name% &&cn'existe pas !"
    prefix:
      set_success: "&&aLe prefix de &&6%rank_name% &&aa //et//e changer en &&r%rank_prefix% &&a."
      get_success: "&&aLe prefix de &&6%rank_name% &&aest &&r%rank_prefix% &&a."
      unknow_rank: "&&cLe rank &&6%rank_name% &&cn'existe pas !"
    power:
      set_success: "&&aLe power de &&6%rank_name% &&aa //et//e changer en &&r%rank_power% &&a."
      get_success: "&&aLe power de &&6%rank_name% &&aest &&r%rank_power% &&a."
      unknow_rank: "&&cLe rank &&6%rank_name% &&cn'existe pas !"
      unknow_number: "&&cLa valeur 'power' doit être un nombre !"

config:
  joinmsg: "%player_prefix% %player_name% &&7a rejoin le server."
  chat:
    allow_plugin_chat: true
    allow_plugin_tablist: true
    allow_plugin_scoreboard: true
  
    format: "%player_prefix% %player_name% : %event_message%"
    admin_chat_format: "&&1(AdminChat) %player_prefix% &&r%player_name% : %event_message%"
    nick_format: "%player_prefix% %player_nick_name% : %event_message%"
    private_msg_format_me: "&&7//a %player_prefix% %player_name% : %message%"
    private_msg_format_other: "&&7de %player_prefix% %player_name% : %message%"
    
    admin_chat_error: "&&cTu a //et//e exclu de l'admin chat, vous avez //et//e rediriger sur le canal public."
    mute_msg: "&&4Tu est mute donc tu ne peut pas parler."
    #Pour voir le nom normal d'un joueur nickname en admin (avec la permission dotplugin.shownick)
    allow_show_nick: true
    show_nick_format: "%player_prefix% %player_nick_name%(%player_name%) : %event_message%"
  tablist:
    format: "%player_prefix% %player_name%"
    nick_format: "%player_prefix% %player_nick_name%"
    allow_show_nick: true
    show_nick_format: "%player_prefix% %nick_name%(%player_name%)"
  scoreboard:
  - '&&b=-=-=-=-=-=-=-=-=-=-=-='
  - '&&bJoueur: &&3%online_player%'
  - '&&bCoins: &&3%player_coins%'
  - '&&bMob Tuer: &&3%player_mob_kill%'
  - '&&bMort Totale: &&3%player_death%'
  - '&&b=-=-=-=-=-=-=-=-=-=-=-='
  report:
    report_gui_format: "&&bReport: &&c%player_name%"
    report_view_name: "&&bReports"
    report_list: ["spambow","forcefield"]
    reports:
      spambow:
        name: "&&cSpamBow"
        material: "bow"
      forcefield:
        name: "&&cForceField"
        material: "iron_sword"

donne:
  spawn:
  lobby:
  
coin:
  addCoinWhenJoin: 20
  player:
